Repository cloudera-labs/cloudera.cluster, pull requests merged in 2023-12, with the labels that each got.

#168 Update logging and error handling for CM API modules
  plugins/doc_fragments/cm_options.py
  plugins/module_utils/cm_utils.py
  plugins/modules/assemble_cluster_template.py
  plugins/modules/cm_endpoint_info.py
  plugins/modules/cm_resource.py
  plugins/modules/cm_resource_info.py
  plugins/modules/cm_version_info.py
Labels: enhancement, validated

#167 Add assemble template role
  roles/assemble_template/defaults/main.yml
  roles/assemble_template/meta/argument_specs.yml
  roles/assemble_template/tasks/main.yml
Labels: enhancement, validated

#163 ldap search filters - allow literal expression
  roles/cloudera_manager/external_auth/templates/external_auth_configs.j2
Labels: enhancement, validated

#170 Add changes to run ansible.builtin.template locally
  roles/assemble_template/meta/argument_specs.yml
  roles/assemble_template/tasks/main.yml
Labels: bug, validated

#171 Allow complex expressions in external authentication LDAP search filters
  roles/cloudera_manager/external_auth/templates/external_auth_configs.j2
Labels: bug, validated

#182 Remove deprecated "warn" argument from shell and command module calls
  roles/cloudera_manager/license/tasks/enterprise.yml
  roles/cloudera_manager/repo/tasks/main-RedHat.yml
Labels: bug, validated

#183 Update role API for assemble_template
  roles/assemble_template/meta/argument_specs.yml
Labels: documentation, validated
