Repository cloudera-labs/cloudera.cluster, pull requests merged in 2023-11, with the labels that each got.

#119 CDH to CDP Upgrade : YARN Queues are not migrated
  roles/deployment/cluster/templates/upgrade_scripts/fs2cs.j2
Labels: bug, validated

#123 use spark_on_yarn_service dependency for hive in CDH only
  roles/config/cluster/base/templates/configs/inter-service-dependencies.j2
Labels: bug

#152 Adds 7.1.9 QueueManager for postgresql
  roles/config/cluster/base/templates/configs/databases-7.1.9.j2
  roles/config/cluster/base/vars/main.yml
  roles/deployment/definition/defaults/main.yml
Labels: enhancement, validated

#159 Remove extra quote from databases-7.1.0 config condition
  roles/config/cluster/base/vars/main.yml
Labels: bug

#151 Allow selection of cluster deployed from cluster.yml
  roles/deployment/cluster/tasks/main.yml
Labels: enhancement, validated

#158 Fix typo - Feature qmanagerdb
  roles/config/cluster/base/templates/configs/databases-7.1.9.j2
  roles/deployment/definition/defaults/main.yml
Labels: validated

#161 Filter AWS_S3 service from host template validation check
  roles/cloudera_manager/external_account/tasks/main.yml
  roles/verify/parcels_and_roles/tasks/check_cluster.yml
  roles/verify/parcels_and_roles/tasks/check_cluster_config_roles.yml
Labels: bug

#164 Create module and action plugins for assemble_cluster_template
  plugins/action/assemble_cluster_template.py
  plugins/modules/assemble_cluster_template.py
Labels: enhancement, validated
