Repository cloudera-labs/cloudera.cluster, pull requests merged in 2023-09, with the labels that each got.

#127 support CDP 7.1.9 / CM 7.11.3 deployment
  roles/config/cluster/base/templates/configs/logdirs-7.1.9.j2
  roles/config/cluster/base/templates/configs/logdirs-ranger-spooldirs-7.1.9.j2
  roles/config/cluster/base/vars/main.yml
Labels: enhancement, validated

#125 Add documentation build workflows
  .github/workflows/publish_docs.yml
  .github/workflows/validate_pr.yml
  .github/workflows/validate_pr_docs.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/links.yml
  docsbuild/.gitignore
  docsbuild/antsibull-docs.cfg
  docsbuild/build.sh
  docsbuild/cloudera.css
  docsbuild/conf.py
  docsbuild/requirements.txt
  galaxy.yml
  plugins/doc_fragments/cm_options.py
  plugins/filter/append_database_port.yml
  plugins/filter/cluster_service_role_hosts.yml
  plugins/filter/default_database_port.yml
  plugins/filter/extract_custom_role_groups.yml
  plugins/filter/extract_custom_roles.yml
  plugins/filter/extract_parcel_urls.yml
  plugins/filter/extract_products_from_manifests.yml
  plugins/filter/extract_role_and_group.yml
  plugins/filter/filter_null_configs.yml
  plugins/filter/find_clusters.yml
  plugins/filter/flatten_dict_list.yml
  plugins/filter/format_database_type.yml
  plugins/filter/get_database_collation_mysql.yml
  plugins/filter/get_database_encoding_mysql.yml
  plugins/filter/get_major_version.yml
  plugins/filter/get_product_version.yml
  plugins/filter/to_ldap_type_enum.yml
  plugins/lookup/cm_api.py
  plugins/lookup/cm_service.py
  plugins/module_utils/cm_utils.py
  requirements.yml
Labels: documentation, enhancement, validated

#129 Add 'freeipa_enroll' optional parameter
  docs/freeipa.md
  roles/infrastructure/krb5_client/defaults/main.yml
  roles/infrastructure/krb5_client/tasks/freeipa.yml
Labels: bug, validated
