Repository cloudera-labs/cloudera.cluster, pull requests merged in 2025-07, with the labels that each got.

#313 Fix external_user_mapping module
  plugins/modules/external_user_mappings.py
Labels: bug, validated

#301 Deprecate cluster_service_role_hosts filter
  meta/runtime.yml
  plugins/filter/cluster_service_role_hosts.yml
Labels: deprecated

#296 Deprecate service_role_config and service_role_config_info modules
  plugins/modules/service_role_config.py
  plugins/modules/service_role_config_info.py
Labels: deprecated

#297 Deprecate service_config and service_config_info modules
  plugins/modules/service_config.py
  plugins/modules/service_config_info.py
Labels: validated, deprecated

#299 Deprecate cm_api action
  meta/runtime.yml
Labels: validated, deprecated

#304 Deprecate filter_null_configs filter
  meta/runtime.yml
  plugins/filter/filter_null_configs.yml
Labels: validated, deprecated

#307 Deprecate version filters
  meta/runtime.yml
  plugins/filter/get_major_version.yml
  plugins/filter/get_product_version.yml
Labels: validated, deprecated

#308 Deprecate format_database_type filter
  meta/runtime.yml
  plugins/filter/format_database_type.yml
Labels: deprecated
